# Generated by Django 4.2.7 on 2023-12-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_task_options_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', '-created_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='is_done',
        ),
    ]
